name: Snapshot

on:
  issue_comment:
    types:
      - created

permissions: write-all

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  snapshot:
    name: Snapshot Release
    if: |
      github.event.issue.pull_request &&
      (github.event.comment.body == '/release-pr' || github.event.comment.body == '/snapshot-release')
    runs-on: ubuntu-latest
    steps:
      - name: Enforce write permissions
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ github.event.comment.id }}
        with:
          script: |
            const username = context.actor;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const response = await github.rest.repos.getCollaboratorPermissionLevel({
              owner,
              repo,
              username,
            });
            const permission = response.data.permission
            if (permission === "write" || permission === "admin") {
              await github.rest.reactions.createForIssueComment({
                owner,
                repo,
                comment_id: process.env.COMMENT_ID,
                content: "eyes",
              })
            } else {
              core.setFailed(
              `🚨 Insufficient Permissions! ${username} does not have write permissions`
              )
            }
